version: '3.8'
services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: .
    container_name: backend
    ports:
      - '5000:5000'
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/sports
      - JWT_SECRET=your_secret_key
    volumes:
      - .:/usr/src/app
    command: npm start

volumes:
  mongodb_data:
